### ISSUE TITLE
Supporting `call` for dynamic version

### ISSUE THREAD

**Issue by warsaw** [pdm-project/pdm-backend#122]
I'd like to get your take on a use case.  `version` can be calculated dynamically, which is great for reducing repetition.  Currently only `'file'` and `'scm'` are supported sources of dynamic version information.

I'm experimenting with integrating `pdm` with the Python infra at $work, where we calculate version numbers of packages quite differently.  I've played with trying to use a `pre_build` hook to talk to our infra, and then saving the version number in a file.  I think I can make that work, but it's not ideal (e.g. for several reasons, but f.e. I have to git ignore that file because overwritten during the build process).

What if `pdm` added a `'call'` source for calculating the dynamic version, with the same semantics as say the `pre_build` hook?  Then I could do something like this in my `pyproject.toml` file:

```
version = { call = 'getversion:main()' }
```
where `getversion.py` is a script I can write whose `main()` makes the external infra calls to get the next version number correctly.  Seems like it wouldn't be too hard to add to the `DynamicVersion` class.

WDYT?

**Comment by ofek** [comment]
I found this while looking at that other issue. Hatching supports this use case: https://hatch.pypa.io/latest/plugins/version-source/code/

**Comment by frostming** [comment]
It is implemented in the new rewritten `pdm-backend`: https://pdm-backend.fming.dev/metadata/#get-with-a-specific-function

Change the build config table to the following

```toml
[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
```
