### ISSUE TITLE
Default wheel build directory conflicts and isn't settable

### ISSUE THREAD

**Issue by warsaw** [pdm-project/pdm-backend#123]
Our infra uses a top level `build/` directory for our internal build artifacts and metadata.  Apparently `WheelBuilder` essentially hard codes `<cwd>/build/` for its build directory too.  What makes this a fatal problem is this code in `wheel.py`:

```python
    def _build(self) -> None:
        build_dir = self.location / "build"
        if build_dir.exists():
            shutil.rmtree(str(build_dir))
```

The effect of this is that if I do `pdm build --no-wheel` my build works fine because the necessary metadata in `build/` is preserved.  But if I do build the wheel (i.e. no arg, or `--no-sdist`, my `build/` directory gets blown away and the metadata that my `pre_build` script creates won't exist by the time the wheel is built, thus failing the build.

I can't find a configuration or `pyproject.toml` setting to change the wheel build directory.

**Comment by frostming** [comment]
I suggest all build configurations should be complete and readable by the build system, rather than rely on the build frontend you use. In this case, the `pre-*` hooks are specific to the PDM. Until standardized by any future PEPs, other frontends can't read them. On the other hand, `pdm-pep517` isn't flexible and extensible enough to add custom build hooks.

I recommend you look at [hatchling](https://github.com/pypa/hatch), you can use it to replace `pdm-pep517`, while still using `pdm` to manage the dependencies.

**Comment by warsaw** [comment]
> All build configurations should be complete and readable by the build system, rather than rely on the build frontend you use.

I think this is proposing that the build backends be independent of the build frontends, in which case I agree!  It would be good to be able to mix and match them as necessary.  F.e. it might even be that we couldn't use one of the common backends and would have to write one ourselves (I hope we don't though!).

> In this case, the pre-* hooks are specific to the PDM. Until standardized by any future PEPs, other frontends can't read them.

Yep, that's not the problem here I think.  I'm happy to rely on PDM-specific hooks in the front-end for now as long as I can find a way to coordinate between the front end and the backend.

> I recommend you look at [hatchling](https://github.com/pypa/hatch), you can use it to replace pdm-pep517, while still using pdm to manage the dependencies.

I need to investigate further, but I don't think `hatchling` or even `pep517` solve the problem.  If I understand [PEP 517's Config setting section](https://peps.python.org/pep-0517/#config-settings) correctly, it ought to be possible for PDM to define a way for the front-end (which reads `pyproject.toml` IIUC) to pass a "build directory" option to `pdm-pep517`.  This could be passed to `WheelBuilder` so `self.location / "build"` wouldn't have to be hard-coded.

I get that `config_settings` isn't at all standardized.  That might be a future direction to engage in with the PyPA/Discourse.  But for now, it might be nice to have support for something like this in `pyproject.toml`:

```
[build-system]
requires = ['pdm-517']
build-backend = 'pdm.pep517.api'
config-settings =
   - build-dir: '.tmp-build'
```

I'm just spitballing here though!

**Comment by ofek** [comment]
The concept of a temporary build directory in the project directory is backend-specific; Hatchling does not do that and never will.

As far as `config_settings` goes, I find it generally useless/unintuitive, so Hatchling uses [environment variables](https://hatch.pypa.io/latest/config/build/#environment-variables).

**Comment by genericmoniker** [comment]
I've run into this issue as well -- project is using `build/` for its own purposes that would be difficult to change.

Is the "closed this as completed" indicating that not using this project is still the recommended solution?

If using a directory in the project is the strategy going forward, could it be named something less likely to conflict, like `pdm-backend-build/`?

**Comment by frostming** [comment]
Put a `pdm_build.py` in the project root with the following content:

```python
def pdm_build_clean(context):
    context.build_dir = context.root / "pdm-backend-build"
```
