### ISSUE TITLE
Support for setuptools-style package discovery

### ISSUE THREAD

**Issue by getglad** [pdm-project/pdm-backend#162]
I'm looking into pdm and was trying to migrate a setuptools configuration but am stuck on a configuration option. setuptools supports a mechanism to explicit declare the location of packages in `pyproject.toml` when you have multiple modules in a repo. Links and examples are below.

Reviewing the pdm-backend [config docs](https://pdm-backend.fming.dev/build_config/), I don't see a similar configuration option. Not sure if I am misunderstanding or if there is something I should be considering.

https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

```
[tool.setuptools.package-dir]
"pkg1" = "lib1"
# pkg1.module1 corresponds to lib1/module1.py
"pkg2" = "lib2"
# pkg2.module2 corresponds to lib2/module2.py
```

**Comment by frostming** [comment]
Yes, we don't have the equivalent config. But this feature is trivial to achieve, the package-dir in setuptools config is no more than a rename mapping `pkg1 -> lib1, pkg2->lib2`. Why not just name the directory as `pkg1` and `pkg2`? Then you can include them by:


```toml
[tool.pdm.build]
includes = ["pkg1/", "pkg2/"]
```
