### ISSUE TITLE
[PEP 420] Automatically discover nested namespace packages

### ISSUE THREAD

**Issue by ItsAleph** [pdm-project/pdm-backend#168]
## Background

Not sure whether this a problem with pdm, pdm-backend or a mix of both, but since managing project with pdm while using poetry's masonry as build backend works fine, i believe the issue is on pdm-backend's end. A similar issue was opened on pdm's repo (pdm-project/pdm#761), after #8 was merged, but was not resolved (or was, but left others without a solution). Might be related too.

## The Problem

For example, let's take a project i develop an extension for, it's basic structure is as follows:
```
disnake/
  __init__.py
  ... # Various modules
  ext/
    # Namespace module (no __init__.py)
    ... # Some built-in namespace packages
pyproject.toml
```
And the namespace package is:
```
disnake
  ext/
    plugins/
        __init__.py
        ...
pyproject.toml
```
And finally let's do same actions with pdm-backend and poetry's masonry:
```sh
myproject> pdm venv create # We'll work in virtualenv mode
myproject> pdm init # Init pyproject.toml
myproject> pdm add disnake # Primary package
myproject> pdm add git+https://github.com/LiTechO/disnake-ext-plugins@8f2f7d558fc8966d7ba606ff9ceec1627dfc9919 # Namespace package, uses commit at which build backend was Masonry
myproject> pdm install # Just to make sure everything is installed
```
```sh
myproject> poetry init # Init pyproject.toml
myproject> poetry add disnake # Primary package
myproject> poetry add git+https://github.com/LiTechO/disnake-ext-plugins@2d5c4d31f6491151929710f0d89bf75b70a26262 # Namespace package, uses commit at which build-backend was pdm-backend
myproject> # Poetry doesn't support PEP 621 and uses virtualenv by default
myproject> poetry install # Just to make sure everything is installed
```
Afterwards, we'll inspect the resulting venv:
```sh
myproject> # This is not the exact output
myproject> tree ~/.cache/pypoetry/virtualenvs/myproject-XXXXXXXX-py3.11/lib/python3.11/site-packages/
...
disnake/
  __init__.py
  ...
  ext/
    ...
    plugins/
      __init__.py
      ...
disnake-X.Y.Z.dist-info/
disnake_ext_plugins-X.Y.Z.dist-info/
...
```
```sh
...
disnake/
  __init__.py
  ...
  ext/
    ...
    # No plugins
disnake-X.Y.Z.dist-info/
# No .pth either
disnake_ext_plugins-X.Y.Z.dist-info/
...
```
As you can see, poetry/masonry installed disnake-ext-plugins right into disnake/ext/ (afaik standard setuptools would do the same), while pdm/pdm-backend only built dist-info.
In case of pdm-backend, if we try to import the namespace package, we get this:
```py
>>> from disnake.ext import plugins
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'plugins' from 'disnake.ext' (unknown location)
>>> 
```
No idea why, but it's not the default error message (default is `ImportError: cannot import name '{NAME}' from '{MODULE}' ({PATH})`.

## Expected

PDM/PDM-Backend to behave the same or at least similarly to poetry/masonry or pip/setuptools.

## Actual result

PDM/PDM-Backend fails to install namespace packages.

## Additional info

OS: Linux 6.3.1-arch1-1 x86_64
Python: 3.11.3
PDM: 2.6.1
PDM-Backend: 2.0.6
Poetry/Masonry: 1.4.2

**Comment by pawamoy** [comment]
Personally I configure like this for namespace packages:

```toml
[tool.pdm.build]
package-dir = "src"
includes = ["src/mkdocstrings_handlers"]
```

```console
% tree -L 3 src
src
└── mkdocstrings_handlers
    ├── python
    │   ├── __init__.py
    │   └── etc
    └── py.typed
```

**Comment by ItsAleph** [comment]
> Personally I configure like this for namespace packages:
> 
> ```toml
> [tool.pdm.build]
> package-dir = "src"
> includes = ["src/mkdocstrings_handlers"]
> ```
> 
> ```
> % tree -L 3 src
> src
> └── mkdocstrings_handlers
>     ├── python
>     │   ├── __init__.py
>     │   └── etc
>     └── py.typed
> ```

Wow, thanks! Apparently that worked, but IMO the issue still persists, and layout mentioned in the original message should be supported too.

**Comment by pawamoy** [comment]
In your case I think the issue is that you have a namespace package inside of a regular package. Does it actually work when you install both this package and other disnake plugins? IMO the plugins wouldn't be importable.

**Comment by ItsAleph** [comment]
Not sure whether that's the problem, at least neither [PPA guide](https://packaging.python.org/en/latest/guides/packaging-namespace-packages/) nor pep 420 mentions anything that'll go against it. Though after re-reading the former one, i noticed a warning:
> Because `mynamespace` doesn’t contain an `__init__.py`, `setuptools.find_packages()` won’t find the sub-package. You must use `setuptools.find_namespace_packages()` instead or explicitly list all packages in your `setup.py`.
This suggests that this is the default/standard behaviour of a build backend, so it looks like technically pdm-backend does everything correctly. However, i think at least some sort of a note or a FAQ entry should be added to the docs, because not everyone have time to research old issues or test out multiple configurations, especially in such an unoptimized workflow (change pyproject.toml, commit/push changes, mkcd into new folder, init new project, create venv, add deps, try importing, check out what's inside the venv, repear - and that's for a matrix of three tools: pdm, pdm-backend and poetry/masonry). If this is desired, i'll happily make a PR.
