### ISSUE TITLE
Clarify order of `pdm_build_initialize` and `pdm_build_clean`

### ISSUE THREAD

**Issue by tgolsson** [pdm-project/pdm-backend#172]
The `pdm_build_clean` hook isn't included at all on the docs page, and from the code it's not super-clear which one happens first. Naively I thought `initialize` would happen first, but cleaning happens before initialize. Not super-obvious. :-) 

<img width="232" alt="image" src="https://github.com/pdm-project/pdm-backend/assets/8234817/76846909-e158-4d86-ab38-a8a9a1296d75">

Depending on preferred solution I'd be happy to contribute a patch to either docs or dig into order of hooks. :-)

**Comment by szandara** [comment]
I think I have fixed it https://github.com/pdm-project/pdm-backend/pull/174/files

**Comment by frostming** [comment]
Yes, please improve the docs
