### ISSUE TITLE
scm versionning fails when package is not top-level directory

### ISSUE THREAD

**Issue by Lawouach** [pdm-project/pdm-backend#175]
Hello there,

Say you have a monorepo approach and your top-level `.git` directory and your `pyproject.toml` resides in a subdirectory, then it seems `pdm buid` fails to pick up the version and always sets it to `0.0.0`.

I was able to reproduce with a simple project into a subdir of the top-level directory containing the `.git` directory and using:

```toml
[project]
name = "mylib"
dynamic = ["version"]
description = ""
authors = [
    {name = "", email = ""},
]
dependencies = []
requires-python = ">=3.11"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm]
version = { source = "scm" }
```

 ```
$ cd /tmp/top
$ ls .git
branches  COMMIT_EDITMSG  config  description  HEAD  hooks  index  info  logs  objects  refs
$ cd ./mylib
$ git tag
0.1.0
$ pdm build
Building sdist...
Built sdist at /tmp/top/mylib/dist/mylib-0.0.0.tar.gz
Building wheel...
Built wheel at /tmp/top/mylib/dist/mylib-0.0.0-py3-none-any.whl
 ```

**Comment by Lawouach** [comment]
As a side, maybe related, question. The code seems to run this command

```
git describe --dirty --tags --long --match *.*
```

I was curious why that match pattern?

For instance in that repo, if I run:

```
$ git describe --dirty --tags --long --match *.*
fatal: No names found, cannot describe anything.
```

but with a different pattern:

```
$ git describe --dirty --tags --long --match *.*.*
0.1.0-0-g919ff2e
```

I'm not sure why this was the pattern you went for?

**Comment by frostming** [comment]
> I was curious why that match pattern?

Wrap the `*.*` with single quotes to avoid being expanded and you will get the right info. So it isn't the issue.
