### ISSUE TITLE
sources-includes documentation confusion

### ISSUE THREAD

**Issue by Lawouach** [pdm-project/pdm-backend#184]
Hi,

The documentation on `sources-includes` says:

```
The patterns in source-includes will be automatically excluded by the wheel distribution.
```

The `excluded` term is confusing. Is that a mistake?

**Comment by frostming** [comment]
no, these patterns will be included by sdist but excluded by wheel distribution. They are different formats

**Comment by Lawouach** [comment]
Okay. I guess the phrasing is confusing to me but if it's clear to you, then let's close this.
