### ISSUE TITLE
pdm-backend should not normalize names in project metadata

### ISSUE THREAD

**Issue by warsaw** [pdm-project/pdm-backend#185]
In the [long thread on discuss.python.org](https://discuss.python.org/t/change-in-pypi-upload-behavior-intentional-accidental-pebkac/27707/1) several problems related to normalization of package names have been identified.  Specifically, `pdm-backend`'s behavior of normalizing the package name in the project metadata causes PyPI to incorrectly display the package's intentional name and `pip install` instructions.

Context is contained in the thread linked above.

FWIW, I actually don't care about the file names - normalize away!  I just want the metadata project name to match what I put in `pyproject.toml`!

**Comment by frostming** [comment]
It is the behavior of [pyproject-metadata](https://github.com/FFY00/python-pyproject-metadata/blob/604d3889880043831299c1a8fffaaa5d67e2ff8c/pyproject_metadata/__init__.py#L198), can you report the issue there?

**Comment by warsaw** [comment]
Code link: https://github.com/FFY00/python-pyproject-metadata/blob/604d3889880043831299c1a8fffaaa5d67e2ff8c/pyproject_metadata/__init__.py#L198

Maybe just removing line 198 does the trick?

**Comment by warsaw** [comment]
Thank you!  I've confirmed this fixes the problem in the metadata.  Unfortunately, the project name is still getting normalized on PyPI, so I will follow up over there.

**Comment by warsaw** [comment]
This is not solved: https://github.com/pypi/warehouse/issues/13992#issuecomment-1608207741

But I think this is a bug in `pdm` front-end, not `pdm-backend`.  @frostming what do you think?  Should I report it over there?

**Comment by frostming** [comment]
But twine is doing the same: https://github.com/pypa/twine/blob/0bb428c410b8df64c04dc881ac1db37d932f3066/twine/package.py#L146

Maybe only flit doesn't normalize it? What is the problem caused by this BTW?

**Comment by frostming** [comment]
Okay, hatch also doesn't normalize, I will change it in PDM.

**Comment by warsaw** [comment]
I think both twine and flit do the right thing.  I had a long discussion with @dstufft about this, and he gave me a little bit of Python code to test what those tools do when uploading to PyPI).  Here's what I've seen:

PDM:
```
FieldStorage('name', None, 'flufl-enum')
127.0.0.1 - - [26/Jun/2023 13:51:49] "POST / HTTP/1.1" 200 0
FieldStorage('name', None, 'flufl-enum')
127.0.0.1 - - [26/Jun/2023 13:51:49] "POST / HTTP/1.1" 200 0
```

flit:
```
FieldStorage('name', None, 'flufl.enum')
127.0.0.1 - - [26/Jun/2023 13:55:12] "POST / HTTP/1.1" 200 0
FieldStorage('name', None, 'flufl.enum')
127.0.0.1 - - [26/Jun/2023 13:55:21] "POST / HTTP/1.1" 200 0
```

twine:
```
FieldStorage('name', None, 'flufl.enum')
127.0.0.1 - - [26/Jun/2023 13:58:34] "POST / HTTP/1.1" 200 0
FieldStorage('name', None, 'flufl.enum')
127.0.0.1 - - [26/Jun/2023 13:58:34] "POST / HTTP/1.1" 200 0
```

So you can see that only PDM is sending `flufl-enum` while both twine and flit send `flufl.enum`.  @dstufft told me that this is the only information PyPI uses to set the visible name and `pip install` instructions on a package's home page.  Although in the future it might read the package's metadata for this, currently the upload `name` is what's used. 

You can see the effects of this very clearly at: https://pypi.org/project/flufl-enum/

(I'm not sure if the canonical URL is also taken from that, but I care a little less about that because https://pypi.org/project/flufl.enum/ does redirect.)

**Comment by warsaw** [comment]
> Okay, hatch doesn't normalize either, I will change it in PDM.

Thanks!  Is there an issue over in PDM I can follow?

**Comment by frostming** [comment]
> Thanks! Is there an issue over in PDM I can follow?

https://github.com/pdm-project/pdm/issues/2057

**Comment by warsaw** [comment]
Thank you!
