### ISSUE TITLE
[Feature Request]How can we custom the format of the dynamic version generated by pdm when we use scm?

### ISSUE THREAD

**Issue by shenmishajing** [pdm-project/pdm-backend#208]
It's a common case to build and publish the package to PyPI at tagged commits and to TestPyPI on untagged commits. However, both PyPI and TestPyPI does not accept version string with a local version suffix. Therefore, it will be helpful to add a 'dev' suffix only when we are not exactly on a tag and use the local version '+dxxx' or '+gxxx' only when there is uncommited changes. So, how can we customize the formattion of the version string generated by pdm? If it's not supported now, can we support it in the future?

**Comment by shenmishajing** [comment]
@frostming cc :) 👍

**Comment by whitequark** [comment]
@frostming I'd also like to have this functionality for Amaranth https://github.com/amaranth-lang/amaranth/actions/runs/8102317673/job/22144699565

**Comment by whitequark** [comment]
Thank you!
