### ISSUE TITLE
Use `git describe` for generating project version from SCM

### ISSUE THREAD

**Issue by g0di** [pdm-project/pdm-backend#215]
PDM backend currently allow to fill one's project `version` [automatically based on git tag](https://backend.pdm-project.org/metadata/#read-from-scm-tag-supporting-git-and-hg)

I'm not sure how it actually does it (which git command) but I found recently that `git describe` was really good at generating version numbers for my applications based on previous tag.  Apparently, pdm-backend is not using git describe because the output is really different. 

Is there a way to ask PDM to use `git describe` for generating project version?
If not, is this something that could be easily added?

Thx!

**Comment by pawamoy** [comment]
How do you use `git describe` to generate version numbers?

**Comment by pawamoy** [comment]
Well PDM does the same thing while conforming to PEP 440, i.e. `0.10.0.dev3+gd490ed7` instead of `0.10.0-3-gd490ed7`. It will also add the current date if the repository is dirty (uncommited changes, excluding new untracked files): `0.10.0.dev3+gd490ed7.d20240219`.

**Comment by g0di** [comment]
Now that you compare it this way, it looks mostly the same. I think I might be fine using the existing PDM implementation (considering its even PEP compliant). My apologizes then. I'm closing!

**Comment by pawamoy** [comment]
@ryukinix, sorry, I don't know if it's possible to prevent appending the date part when the repo is dirty.
