### ISSUE TITLE
cleaning up the source directory after build

### ISSUE THREAD

**Issue by dgrigonis** [pdm-project/pdm-backend#216]
Hello,

I am running the backend with `run-setuptools = true`.

And I am compiling several extensions using cython.

The issue is that `.c` files are left in source directory. `src/my_pkg/file.c`

And I am looking for solution of getting rid of them automatically.

So I see 2 possible solutions:
a) Some clever configuration for this in cython or extending build classes run by setuptools
b) running extra hook as part of `pdm build` and doing it manually

I would appreciate any insight into a), but I appreciate that this might not be directly related to this backend, but more to `setuptools`.

And I would like to know if there is something for b).

Regards,
DG

**Comment by frostming** [comment]
Whoever creates the file is responsible for clearing it, and I think the correct person is cython or setuptools

**Comment by dgrigonis** [comment]
Fair, thanks.
