### ISSUE TITLE
.dist-info folder name incorrectly normalized

### ISSUE THREAD

**Issue by f3flight** [pdm-project/pdm-backend#218]
I ran into an issue when using `pipdeptree` project with an environment containing `flufl.lock==8.0.2`. This package (wheel) is built with `pdm-backend` v2.1.4 (I have also rebuilt with latest 2.1.8 and result was the same). What I found is that upon migration from `pdm-pep517` v1.0.4 to `pdm-backend` 2.x, the folder name inside the wheel changed:
![image](https://github.com/pdm-project/pdm-backend/assets/6680260/51441bbc-afcb-46eb-9bb7-b4bdac7f1576)
Now, this matters because certain software, such as `setuptools`, restores "project_name" and "key" from the folder name when creating `DistInfoDistribution` objects. In which case with`pdm-backend` 2.x the project_name becomes `flufl-lock` instead of `flufl.lock`. And then `pipdeptree` assumes that it can compare `DistInfoDistribution.key` with `Requrement.key` and fails to do so. A bit more detail cane be found here - https://github.com/pypa/setuptools/issues/4250.
Also posted here for awareness - https://github.com/tox-dev/pipdeptree/issues/324

**Comment by frostming** [comment]
I think pdm-backend is doing correctly as specified in [PyPA User Guide](https://packaging.python.org/en/latest/specifications/binary-distribution-format/#escaping-and-unicode)

And it's pipdeptree that should fix the comparison logic.

**Comment by f3flight** [comment]
Fair enough. In this case I feel like setuptools could be more consistent with keys and should derive "project_name" from folder name, if normalization is not enforced but a recommendation only at this time. Feel free to close, thanks!
