### ISSUE TITLE
Allow filtering tags when using SCM to determine the version

### ISSUE THREAD

**Issue by mezuzza** [pdm-project/pdm-backend#219]
I've used PDM in a few monorepos. In each one, I need to build different projects which all have dynamic SCM versioning enabled. Each project has it's own versioning determined by git tags. e.g. `project-a/0.1.1` and `project-b/2.1.1`. However, when using scm versioning, only the most recent of those tags will be used and only one project will derive a proper version number.

The workaround for git is to use a `call` based version and reuse most of the same machinery (see below for the workaround).

I don't know the equivalent for mercurial, but for git, we simply need to be able to provide an argument for the `--match` command line argument for git describe [called here in pdm](https://github.com/pdm-project/pdm-backend/blob/d63fec7b3a00a9b4ee50de92c20b29ad5090de4d/src/pdm/backend/hooks/version/scm.py#L187).

Would it be possible to provide a `tag_filter` key in the `tool.pdm.version` table which accepts a glob that is used for the `--match` parameter?

Workaround:
```python
import subprocess

from pdm.backend.hooks.version.scm import (
    DEFAULT_TAG_REGEX,
    Config,
    VersionInfo,
    _git_parse_describe,
    format_version,
    tag_to_version,
)

_PACKAGE_PREFIX = "project-a/"


def get_version():
    branch = subprocess.run(
        ["git", "rev-parse", "--abbrev-ref", "HEAD"],
        capture_output=True,
        encoding="utf-8",
    )

    describe = subprocess.run(
        ["git", "describe", "--long", "--match", f"{_PACKAGE_PREFIX}*", "--dirty"],
        capture_output=True,
        encoding="utf-8",
    )

    tag, distance, node, dirty = _git_parse_describe(describe.stdout.strip())

    version = tag_to_version(Config(DEFAULT_TAG_REGEX), tag)

    return format_version(
        VersionInfo(
            version=version,
            distance=distance or None,
            dirty=dirty,
            node=node,
            branch=branch.stdout.strip(),
        )
    )
```

**Comment by frostming** [comment]
This requirement is reasonable and the solution is also very clear. Would you like to submit a PR?

**Comment by mezuzza** [comment]
I'll try to get to it this week, but no promises.

Do you happen to have any ideas on whether this is an issue for `hg` and if so how you might solve for it? I'll probably leave that as a `TODO` and let that happen in a separate PR.

**Comment by frostming** [comment]
这里有两种情况：
1. If the current commit is associated with a tag, you need to check if it matches the pattern. hg does this through [here].(https://github.com/pdm-project/pdm-backend/blob/74f7a61b645bcc44a173007d277b7dc61783e75f/src/pdm/backend/hooks/version/scm.py#L285)
2. If not, it looks for its ancestors to find the nearest tag, and it accepts a regex pattern: https://github.com/pdm-project/pdm-backend/blob/74f7a61b645bcc44a173007d277b7dc61783e75f/src/pdm/backend/hooks/version/scm.py#L210
