### ISSUE TITLE
The actual behavior of `Dynamic project version` is different from document

### ISSUE THREAD

**Issue by cntvc** [pdm-project/pdm-backend#234]
In the document [`Get with A Specific Function`](https://backend.pdm-project.org/metadata/#get-with-a-specific-function), the actual behavior is different from the documentation.

---

example config:
```toml
[tool.pdm.version]
source = "call"
getter = "mypackage.get_version"
```

I execute the `pdm build` command, and then get some errors:
```cmd
pdm.backend.exceptions.ConfigError: Invalid expression, must be in the format of `module:attribute`.
```

After I modify the config file, it can run correctly.
```diff
- getter = "mypackage.get_version"
+ getter = "mypackage:get_version"
```

I'm not sure if it is a document or a code error.

Env:
- Python: 3.11
- PDM: 2.15.0

**Comment by frostming** [comment]
Wrong document, thanks

**Comment by cntvc** [comment]
Should I create PR?

**Comment by frostming** [comment]
why ask? go ahead
