### ISSUE TITLE
Support map "includes" to a different directory in site-packages

### ISSUE THREAD

**Issue by xulongwu4** [pdm-project/pdm-backend#239]
Currently the `includes` will be copied to `site-packages` as it is. For example, if I have `includes = ["path/to/foo"]`, then `path/to/foo` will appear in the `site-packages`. Can we support mapping this `path/to/foo` in the source tree to a different directory in `site-packages`? For example, I might want to be able to do `import foo` after installing my package, so I would want `path/to/foo` in the source tree to be installed to `foo` in `site-packages`. That adds flexibility in the backend.

**Comment by frostming** [comment]
set `package-dir` config to `path/to`: https://backend.pdm-project.org/build_config/#the-src-layout, which means `path/to/foo` will be importable as `import foo`

This works the same as the equivalent in setuptools:

```
setup(
    package_dir={"": "/path/to"}
)
```

**Comment by xulongwu4** [comment]
Yeah `package_dir` works, but it is a common value for all `includes`. I would like to have a way to customize the installation path for each `includes`.

For instance, if I am using the `src` layout, so the `package_dir` is by default `src`. Now my package in `src/mypackage` would be installed correctly. If I also have `path/to/foo` outside `src` and I want it to be installed to `site-packages/foo`, there would be no way to do it as far as I know.

**Comment by frostming** [comment]
Is there any special reason not putting it inside `src/` instead?
