### ISSUE TITLE
Support different versions of packages for different environments

### ISSUE THREAD

**Issue by mezuzza** [pdm-project/pdm-backend#252]
One case I'm running into which may or may not be unique:
I have a monorepo at work where we're building multiple services and some services share a package. We'd like to use the local files as an editable when developing, but use a specific version from our internal repository when running in production. In essence, I'm trying to manage different environments using dependency groups.

My attempt at this was to add the same dependency in two different dependency groups with different versions:

```toml
[project]
dependencies = [
  "mypkg>=0.1.0"
]

[tool.pdm.dev-dependencies]
dev = [
  "-e file:///${PROJECT_ROOT}/../mypkg#egg=mypkg",
]
```

But the lock file doesn't support this afaict. It produces this:

```toml
[[package]]
name = "mypkg"
version = "0.1.1.dev17"
requires_python = ">=3.12"
editable = true
path = "../mypkg"
summary = "My Package"
groups = ["default", "dev"]
dependencies = [
 ...
]
```

The ask is whether it's possible to track a more complex configuration:

```toml
[[package]]
name = "mypkg"
groups = {
  "default" = {
    version = "0.1.0"
    requires_python = ">=3.12"
    summary = "My Package"
    dependencies = [...]
  },
  "dev" = {
    versions = "0.1.1.dev17"
    requires_python = ">=3.12"
    editable = true
    path = "../mypkg"
    summary = "My Package"
    groups = ["default", "dev"]
    dependencies = [
     ...
    ]
  }
}
```

Another option would be to support multiple lock files which could manage different environments: Essentially use `pdm.lock` for local development and a `pdm.prod.lock` for production deployments.

A final option I was considering, but is also fraught with issues is using the `extra` environment marker. The idea would be to install a specific version per environment.

All of these options seem to require some changes I believe, but would love some feedback on what approach pdm might suggest here

**Comment by frostming** [comment]
> Another option would be to support multiple lock files which could manage different environments: Essentially use `pdm.lock` for local development and a `pdm.prod.lock` for production deployments.

https://pdm-project.org/en/stable/usage/lockfile/#specify-another-lock-file-to-use

**Comment by mezuzza** [comment]
Thanks for the pointer. I misunderstood the intention for that feature, but the reason I originally rejected it in my head was that it's not guaranteed that the lock file will be kept in sync.

Is the expectation that you can use `pdm lock --update-reuse-installed -L pdm.prod.lock`? That seems a bit error prone, but we'll probably make do if that's required.
