### ISSUE TITLE
Support for documentation in org-mode format

### ISSUE THREAD

**Issue by hsunner** [pdm-project/pdm-backend#257]
## pdm throws an exception for an org-mode readme

I applied PDM to an existing project in which I have docs written in org-mode markup format. AFAIK this is a supported readme format for e.g. GitHub. However, pdm throws an exception when I specify an org-mode readme.

I have the following in my pyproject.toml:
```
[project]
readme = "README.org"
```

When I run `pip install -e .` on my project I get the following exception `pdm.backend.exceptions.ValidationError: project.readme: Could not infer content type for readme file "README.org"`. The error is shown from 
```
File "pdm/backend/config.py", line 65, in validate
    raise ValidationError(e.args[0], e.key) from e
```

## Should I fix this, and what would that entail?

I'd like to understand how big of an undertaking it would be to get this working. Is it only that org-mode needs to be recognised, or does something need to be parsed out from the readme file? I have not used PDM or pyproject.toml before, so maybe there is a whole lot of functionality around documentation that needs to be supported for org-mode?

If not, simply making pdm aware of org-mode ("infer content type" for org-mode) does sound like something I could try my hand at, if it's the maintainer's opinion that this makes sense.

**Comment by hsunner** [comment]
Hi!
Thanks for the exhaustive and fast reply. I understand the background better now, and it does not seem to be meaningful to add support for other markup formats natively in PDM as this would introduce dependencies for format translators.

I assume that you can add build-time actions that will do the translation using external tools (eg pandoc) as part of the build process to generate the .md or .rst file, so that it can be solved when required. For me, I will translate the readme to .rst.

**Comment by frostming** [comment]
Thanks, you can also have it implemented via either [backend hooks](https://backend.pdm-project.org/hooks/#modify-the-project-metadata) or [pre_build](https://pdm-project.org/en/latest/reference/api/#pdm.signals.pre_build)
