### ISSUE TITLE
Use fallback version when no Git tags are found?

### ISSUE THREAD

**Issue by pawamoy** [pdm-project/pdm-backend#269]
Currently, it looks like the fallback version is only used when pdm-backend completely fails reading anything from the SCM, i.e. the project is *not* a Git repository. When the project *is* a Git repository, but doesn't have any tags, pdm-backend will infer a version like `0.1.devN+gHASH.dDATE`.

I'm in a situation where uv refuses to solve my dependencies, because my current project dev-depends on a library that depends on back the current project, and since the current project version is computed as 0.1.etc (because it doesn't have Git tags[^1]) , it's not compatible with what the library requires, and uv fails. See https://github.com/astral-sh/uv/issues/8148. I think uv should not fail, or have a config flag to ignore the current project version.

[^1]: It doesn't have Git tags for various reasons. For example it could be a contributor fork, and GitHub doesn't copy tags when creating a fork.

In the meantime, I'm trying to use the fallback version, but since my project is a Git repo, the fallback version doesn't seem to be used. That's also what I gather from reading the code:

```python
            scm_version = get_version_from_scm(
                context.root, tag_regex=tag_regex, tag_filter=tag_filter
            )
            if scm_version is None:  # <-- probably false, and branch is not entered
                if fallback_version is not None:
                    version = fallback_version
```

Do you think it would be feasible to use the fallback version if no tags were found, even though the project is a proper Git repository?

**Comment by pawamoy** [comment]
OK I found a uv-based solution (see https://github.com/astral-sh/uv/issues/8148#issuecomment-2476395325), this issue can be closed :slightly_smiling_face:

**Comment by pawamoy** [comment]
Actually that led to other issues. So I used my brain and found a pdm-backend solution:

```toml
[tool.pdm.version]
source = "call"
getter = "scripts.get_version:get_version"
```

```python
# scripts/get_version.py
import re
from pathlib import Path

from pdm.backend.hooks.version import Version, SCMVersion, get_version_from_scm, default_version_formatter

_root = Path(__file__).parent.parent
_changelog = _root / "CHANGELOG.md"
_changelog_version_re = re.compile(r"^## \[(\d+\.\d+\.\d+)\].*$")
_default_scm_version = SCMVersion(Version("0.0.0"), None, False, None, None)


def get_version():
    scm_version = get_version_from_scm(_root) or _default_scm_version
    if scm_version.version <= Version("0.1"):  # Missing Git tags?
        if _changelog.exists():
            with _changelog.open() as file:
                for line in file:
                    if match := _changelog_version_re.match(line):
                        scm_version = scm_version._replace(version=Version(match.group(1)))
                        break
    return default_version_formatter(scm_version)
```

**Comment by GPHemsley-RELX** [comment]
`git_parse_version()` and `hg_parse_version()` hardcode "0.0" rather than using the fallback version:
https://github.com/pdm-project/pdm-backend/blob/6c339b6a2f8a9e454e9c240cca374aa0d9148ec1/src/pdm/backend/hooks/version/scm.py#L183-L218
https://github.com/pdm-project/pdm-backend/blob/6c339b6a2f8a9e454e9c240cca374aa0d9148ec1/src/pdm/backend/hooks/version/scm.py#L276-L315

In another place, `tag_to_version()` hardcodes "0.0.0":
https://github.com/pdm-project/pdm-backend/blob/6c339b6a2f8a9e454e9c240cca374aa0d9148ec1/src/pdm/backend/hooks/version/scm.py#L165-L180

This seems to me like a bug, orthogonal to the dependency resolution issue OP is trying to solve. I think this issue should be reopened.
